name: Run Python Script

on:
  push:
    branches:
      - main  # Hier kannst du auch einen anderen Branch verwenden
      
permissions:
  contents: write  # Erlaubt den Workflow, auf den Inhalt des Repositories zu schreiben
  
jobs:
  run_script:
    runs-on: ubuntu-latest  # Wählt ein Ubuntu-Image für das Skript

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Läd den Code aus deinem Repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Wählt die Python-Version aus

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Falls du zusätzliche Abhängigkeiten hast, kannst du sie hier installieren:
          # pip install -r requirements.txt

      - name: Clean untracked files
        run: |
          git clean -fdx  # Entfernt alle untracked files (inklusive temporärer Dateien)

      - name: Run Python script
        run: |
          python create_list.py  # Ersetze 'dein_script.py' durch den tatsächlichen Skript-Dateinamen

      - name: Commit generated file
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ublock_filter.txt
          git commit -m "Automatisch generierte Filterliste"
          git push
